In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values

In [5]:
y = dataset.iloc[:, 13].values

## Remove Categorical Variable

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#### There are two labels in the dataset hence we eill require two label encoders

In [9]:
le_X_1 = LabelEncoder()
le_X_2 = LabelEncoder()

In [10]:
X[:, 1] = le_X_1.fit_transform(X[:,1])

In [13]:
X[:,2] = le_X_2.fit_transform(X[:,2])

In [14]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

#### Problem here can be with the the Label Encoder 0,1,2 which needs to be changed to dummy variables because 2 or 1 does 
#### not mean anything except categories which can cause a problem. To Tacke this Change this to Dummy variables

In [15]:
onehotencoder = OneHotEncoder(categorical_features= [1])

In [18]:
X = onehotencoder.fit_transform(X).toarray()

In [23]:
X = X[:, 1:]

#### Split the Variable to training set and test set

In [26]:
from sklearn.cross_validation import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#### Apply Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc = StandardScaler()

In [30]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [31]:
X_test

array([[ 1.62776996, -0.57427105, -0.56129438, ...,  0.66011376,
         0.97628121,  1.62185911],
       [-0.61433742, -0.57427105, -1.33847768, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [-0.61433742,  1.74133801,  0.58347561, ...,  0.66011376,
         0.97628121, -0.41865644],
       ..., 
       [-0.61433742,  1.74133801, -0.76084144, ...,  0.66011376,
        -1.02429504,  0.72775202],
       [ 1.62776996, -0.57427105, -0.0046631 , ...,  0.66011376,
         0.97628121, -1.54162886],
       [ 1.62776996, -0.57427105, -0.81335383, ...,  0.66011376,
        -1.02429504,  1.62356528]])

#### Building Artificial Neural Network

In [32]:
import keras

Using TensorFlow backend.


In [33]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
class_seq = Sequential()

#### Hidden Layer 1

In [36]:
class_seq.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim = 11))

#### Hidden Layer 2

In [37]:
class_seq.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

#### Output Layer

In [38]:
class_seq.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

#### Compiling ANN

In [39]:
class_seq.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [42]:
class_seq.fit(X_train, y_train, batch_size=2, epochs=10, verbose=1)

Epoch 1/10
8000/8000 [==============================] - 4s 447us/step - loss: 0.4030 - acc: 0.8351
Epoch 2/10
8000/8000 [==============================] - 4s 446us/step - loss: 0.4036 - acc: 0.8335
Epoch 3/10
8000/8000 [==============================] - 4s 453us/step - loss: 0.4020 - acc: 0.8337
Epoch 4/10
8000/8000 [==============================] - 4s 445us/step - loss: 0.4023 - acc: 0.8347
Epoch 5/10
8000/8000 [==============================] - 4s 448us/step - loss: 0.4025 - acc: 0.8344
Epoch 6/10
8000/8000 [==============================] - 4s 450us/step - loss: 0.4022 - acc: 0.8339
Epoch 7/10
8000/8000 [==============================] - 4s 451us/step - loss: 0.4023 - acc: 0.8342
Epoch 8/10
8000/8000 [==============================] - 4s 463us/step - loss: 0.4035 - acc: 0.8337
Epoch 9/10
8000/8000 [==============================] - 4s 452us/step - loss: 0.4026 - acc: 0.8334
Epoch 10/10
8000/8000 [==============================] - 4s 441us/step - loss: 0.4035 - acc: 0.8336


#### Predictions

In [47]:
pred = class_seq.predict(X_test)
pred = (pred > 0.5)

In [48]:
from sklearn.metrics import confusion_matrix, classification_report

In [50]:
print(confusion_matrix(y_test, pred))

[[1560   35]
 [ 294  111]]


In [51]:
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.84      0.98      0.90      1595
          1       0.76      0.27      0.40       405

avg / total       0.82      0.84      0.80      2000



In [56]:
print('Accuracy of Test Set = ',(1560+111)*100/2000 , '%')

Accuracy of Test Set =  83.55 %
